plugins {
    id 'fabric-loom' version '1.4-SNAPSHOT'
    id 'maven-publish'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

group project.modGroup
version project.modVersion

base {
    archivesName = project.modBaseName
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    mavenCentral()
    maven {
        name = 'fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = 'SpongePowered'
        url = 'https://repo.spongepowered.org/maven/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraftVersion}"
    mappings "net.fabricmc:yarn:${project.yarnVersion}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loaderVersion}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabricVersion}"

    annotationProcessor "org.spongepowered:mixin:0.8.5"
    modImplementation "org.spongepowered:mixin:0.8.5"

    compileOnly "com.googlecode.json-simple:json-simple:1.1.1"
}

mixin {
    add sourceSets.main, "mixins.exeter.refmap.json"
    config "mixins.exeter.json"
}

processResources {
    inputs.property 'version', project.version
    from(sourceSets.main.resources.srcDirs) {
        include 'fabric.mod.json'
        expand 'version': project.version
    }
}

jar {
    manifest {
        attributes(
                'MixinConfigs': 'mixins.exeter.json',
                'TweakOrder': 0,
        )
    }
}

shadowJar {
    dependencies {
        include(dependency('com.googlecode.json-simple:json-simple:1.1.1'))
        include(dependency('org.spongepowered:mixin'))
    }
    exclude 'dummyThing'
    exclude 'LICENSE.txt'
    classifier = 'release'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
